version: '2'
services:
    gradle2:
        image: mminderbinder/gradle2:oracle-java8
        volumes:
            - ~/code/spring-ref/:/mnt/gradle-projects/spring-ref
        networks:
            - docker1
        command: /sbin/my_init
    redis:
        image: redis:2.8.19
        networks:
            - docker1
        hostname: redis
        expose:
            - "6379"
    postgres:
        image: postgres:9.4.1
        networks:
            - docker1
        hostname: postgres
        expose:
            - "5432"
        volumes:
            - /mnt/springref-data
        env_file:
            - postgres-prod.env
    springref:
        build: .
        networks:
            - docker1
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:8443:8443"
        links:
            - postgres
            - redis
        volumes_from:
            - gradle2
        env_file:
            - springref-prod.env
networks:
    docker1:
        external: true
