gradle2:
    image: mminderbinder/gradle2:oracle-java8
    volumes:
        - ~/Projects/spring-ref/:/mnt/gradle-projects/spring-ref
    command: /sbin/my_init
redis:
    image: redis:2.8.19
    expose:
        - "6379"
    hostname: redis 
postgres:
    image: postgres:9.4.1
    expose:
        - "5432"
    volumes:
        - /mnt/springref-data
    env_file:
        - postgres-prod.env
    hostname: postgres
springref:
    build: .
    ports:
        - "127.0.0.1:8080:8080"
        - "127.0.0.1:8443:8443"
    links:
        - postgres
        - redis
    volumes_from:
        - gradle2
    env_file:
        - springref-prod.env
